apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k6-loadtest.fullname" . }}-config
data:
  config.yaml: |-
    global:
      base_url: {{ .Values.config.global.base_url | quote }}
      defaultDuration: {{ .Values.config.global.defaultDuration | quote }}
      defaultVUs: {{ .Values.config.global.defaultVUs }}
      http_timeout: {{ .Values.config.global.http_timeout | quote }}
      global_token: {{ .Values.config.global.global_token | quote }}
      vars: {{ toJson .Values.config.global.vars }}
    pre_requests: {{ toJson .Values.config.pre_requests }}
    endpoints: {{ toJson .Values.config.endpoints }}
    post_requests: {{ toJson .Values.config.post_requests }}
    bkrepo:
      url: {{ .Values.config.bkrepo.url | quote }}
      username: {{ .Values.config.bkrepo.username | quote }}
      password: {{ .Values.config.bkrepo.password | quote }}
