# 镜像配置
image:
  repository: your-docker-registry/k6-loadtest
  tag: latest
  pullPolicy: IfNotPresent

# 应用内部配置，原来的 config.yaml 内容
config:
  global:
    base_url: "http://your-api-endpoint.example.com"
    defaultDuration: "30s"
    defaultVUs: 300
    http_timeout: "5s"
    global_token: "Bearer your_token_if_needed"
    vars:
      cluster_id: "BCS-K8S-00000"
      project_code: "blueking"
  # bkrepo 配置
  bkrepo:
    url: "http://bkrepo.example.com/generic/blueking/bcs-test" # 上传的基础 URL
    # 仓库的账号密码
    username: "admin"
    password: "blueking"

  # 可在此添加前置请求配置
  pre_requests:
  - name: "获取初始化项目的ProjectID"
    path: "/bcsproject/v1/projects/{project_code}"
    method: "GET"
    extract:
      project_id: "body.data.projectID" # 指明如何提取
      project_name: "body.data.name"
      project_desc: "body.data.description"
  - name: "获取初始化集群的 ClusterName"
    path: "/clustermanager/v1/cluster/{cluster_id}"
    method: "GET"
    extract:
      cluster_name: "body.data.clusterName"
      cluster_desc: "body.data.description"
  # 后置请求配置
  post_requests:
  - name: "还原项目信息"
    path: "/bcsproject/v1/projects/{project_id}"
    method: "PUT"
    body: '{"name": "{project_name}", "description": "{project_desc}"}'
  - name: "还原集群信息"
    path: "/clustermanager/v1/cluster/{cluster_id}"
    method: "PUT"
    body: '{"updater": "admin", "clusterName": "{cluster_name}", "description": "{cluster_desc}"}'
  # 各接口的压测配置
  endpoints:
  # Project Manager
  - name: "更新项目"
    path: "/bcsproject/v1/projects/{project_id}"
    method: "PUT"
    body: '{"name": "test-k6", "updater": "admin", "description": "test-k6"}'
  - name: "获取原生命名空间列表"
    path: "/bcsproject/v1/projects/{project_id}/clusters/{cluster_id}/native/namespaces"
    method: "GET"
  - name: "查询业务列表"
    path: "/bcsproject/v1/business?useBCS=true"
    method: "GET"

  # Cluster Manager
  - name: "查询某个项目下的Cluster列表"
    path: "/clustermanager/v1/projects/{project_id}/clusters"
    method: "GET"
  - name: "查询Cluster列表"
    path: "/clustermanager/v1/cluster"
    method: "GET"
  - name: "查询Cluster"
    path: "/clustermanager/v1/cluster/{cluster_id}"
    method: "GET"
  - name: "更新Cluster"
    path: "/clustermanager/v1/cluster/{cluster_id}"
    method: "PUT"
    body: '{"updater": "admin", "clusterName": "test-k6", "description": "test k6"}'
  - name: "查询集群下的所有master节点列表"
    path: "/clustermanager/v1/cluster/{cluster_id}/master"
    method: "GET"
  - name: "查询集群下的所有node节点列表"
    path: "/clustermanager/v1/cluster/{cluster_id}/node"
    method: "GET"

  # Cluster Resources
  - name: "集群Deployment列表"
    path: "/clusterresources/v1/projects/{project_id}/clusters/{cluster_id}/namespaces/bcs-system/workloads/deployments"
    method: "GET"

# 资源配置（可根据需要调整）
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
